### ISSUE TITLE
Peer to peer review

### ISSUE THREAD

**Issue by bettercallazamat** [Zubenna/my-fullstack-portfolio-index.html#1]
Awesome portfolio, please consider these suggestions:
1) Make your navbar with background color, because it's transparent atm
2) Make margins between social media icons bigger to make it easier to click on them
3) Change the proportion of your images, so they fit in your blocks; also you can use object-fit, object-position properties
4) Try to work on layout of the landing section, when a user enters your portfolio he/she needs to see your description and links right away without scrolling.

**Comment by Zubenna** [comment]
All recommendations have been implemented.
